authentication/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import  SignUp , login_view,logout

app_name ="authentication"

urlpatterns = [

path('signup/', SignUp.as_view(), name='signup'),
path('login/', login_view, name='login'),
path('logout/', logout, name='logout'),





]

# for adding media file settings
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chambre/urls.py
from django.urls import path
from .views import  (chambre ,liste_chambre, supprimer_chambre, Chambre_mise_ajour,search)

app_name="chambre"

urlpatterns = [

    path('ajouter-chambre/', chambre , name='ajouter-chambre'),
    path('liste-chambre/', liste_chambre , name='liste-chambre'),
    path('<int:pk>/delete_chambre/', supprimer_chambre, name='supprimer-chambre'),
    path('editchambre/<int:pk>/', Chambre_mise_ajour.as_view(), name='editchambre'),
    path('search/', search , name='search'),



    ]

contrat/urls.py
from django.urls import path
from .views import *

app_name="contrat"

urlpatterns = [

    path('ajouter-contrat/', contrat , name='ajouter-contrat'),
    path('liste-contrat/', list_contrat , name='liste-contrat'),
    path('<int:pk>/supprimer-contrat/', supprimer_contrat, name='supprimer-contrat'),
    path('<int:pk>/modifier-contrat/', Contrat_mise_ajour.as_view(), name='modifier-contrat'),
    path('locataire-info/', ajouter_locataire_info , name='locataire-info'),
    path('locataire-detail/<int:locataire_id>/',detail_locataire , name='locataire-detail'),
    path('<int:pk>/delete-info/', supprimer_info, name='supprimer-info'),
    path('editinfo/<int:pk>/', Info_mise_ajour.as_view(), name='editinfo'),
    path('search-locataire/', search_maison , name='search-locataire'),




    ]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import HomeView,\
    ItemDetailView,\
    CheckoutView,\
    add_to_cart,\
    remove_from_cart,\
    OrderSummaryView,\
    remove_single_item_from_cart,\
    PaymentMethod,\
    AddCouponView,\
    CategoryListView,\
    RequestRefundView,\
    ProfileView,\
    product
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<category>', CategoryListView.as_view(), name='category-list'),
    path('product/<slug:slug>', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/<slug:slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug:slug>', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='check-out'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>', PaymentMethod.as_view(), name='payment'),
    path('payment/<payment_option>', PaymentMethod.as_view(), name='payment'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('request-refund/<str:ref_code>', RequestRefundView.as_view(), name='request-refund'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

# for adding media file settings
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

houseProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('maison.urls')),
    path('index/', include('chambre.urls')),
    path('index/', include('contrat.urls')),
    path('index/', include('payement.urls')),
    path('index/', include('payement_e_e.urls')),
    path('', include('authentication.urls')),
    path('', include('django.contrib.auth.urls')),




    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

maison/urls.py
from django.urls import path
from .views import  index,List_maison,maison,supprimer_maison, Maison_mise_ajour,detail_maison

app_name ="maison"

urlpatterns = [
path('', index , name='index'),
#path('maison-detail/<slug>/', MaisonDetailView.as_view(), name='maison-detail'),
path('liste-maison/', List_maison.as_view() , name='liste-maison'),
path('ajouter-maison/', maison , name='ajouter-maison'),
path('<int:pk>/delete/', supprimer_maison, name='supprimer-maison'),
path('editMaison/<int:pk>/', Maison_mise_ajour.as_view(), name='editMaison'),
path('maison-detail/<int:pk>/',detail_maison , name='maison-detail'),
]

chambre/models.py
from django.db import models
from maison.models import Maison




STATUS_CHOICES = (
    ('L', 'Libre'),
    ('O', 'Occupee'),
    ('I', 'Indisponible')


)

class Chambre(models.Model):
     type_chambre = models.CharField(max_length=50, null=True, blank=True)
     maison = models.ForeignKey(Maison, on_delete=models.CASCADE, editable=True)
     nom = models.CharField(max_length=25)
     prix = models.FloatField()
     statut = models.CharField(choices=STATUS_CHOICES, max_length=1)




     class Meta:
        ordering = ['nom' ]
        permissions = (('peut voir chamnbre', 'Peut voir chambre'),('peut voir detail chamnbre', 'Peut voir  detail chambre'))

     def get_absolute_url(self):
        return reverse('chambre-detail', args=str([self.pk]))

     def __str__(self):
        return   '{0}'.format( self.nom)

     def is_statut(self):
         if self.statut =='L':
             return True
         return False

maison/models.py
from django.db import models

# Create your models here.

class Maison(models.Model):
    slug = models.SlugField()
    nom_maison = models.CharField(max_length=150, null=False, blank=True, unique=True)
    total_chambre=models.IntegerField()
    quartier = models.CharField(max_length=50, null=False, blank =True)


    class Meta:
        ordering = [ 'nom_maison']
        permissions = (('peut voir les maisons', 'Peut voir les maisons'),)

    def get_absolute_url(self):

       #This generates the url for customer detail.
       #'customer-detail' is the name of the url.
       #Takes argument customer_id
       return reverse("maison-detail", kwargs={
           'slug': self.slug
       })



    def __str__(self):
        return '{0}'.format(self.nom_maison)

maison/forms.py
from  django import forms
from .models import  *


class MaisonForm(forms.ModelForm):
   class Meta:

      model = Maison
      fields = ('slug', 'nom_maison','total_chambre','quartier')
      labels={
          'slug':'Le numero de la chambre',
          'nom_maison':'Nom de la maison',
          'total_chambre':'Nombre de chambre',
          'quartier':'Ville/Quartier'

      }

maison/views.py
from django.views.generic import (CreateView, DeleteView, ListView, FormView, UpdateView, ListView, DetailView)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from .models import Maison
from  contrat.models import  Contrat
from chambre.models import Chambre
from contrat.models import Contrat
from .forms import MaisonForm
from django.shortcuts import  get_object_or_404

# Create your views here.



def index(request):

    maisons = Maison.objects.all().count()
    chambres = Chambre.objects.all().count()
    contrats = Contrat.objects.all().count()



    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits+1
    """
    current_semester = Semester.objects.get(is_current_semester=True)
    no_of_1st_class_students = Result.objects.filter(cgpa__gte=4.5).count()
    no_of_carry_over_students = CarryOverStudent.objects.all().count()
    no_of_students_to_repeat = RepeatingStudent.objects.all().count()
    """
    context = {
        "maisons": maisons,
        "chambres":chambres,
        "contrats":contrats,
        "num_visits":num_visits,

    }

    return render(request, 'maison/index.html', context)



class  List_maison(ListView):
    model = Maison
    template_name = "maison/list_maison.html"



#@login_required
def maison(request):
    """
    Creer nouvelle  maaison
    """
    if request.method == 'POST':
        maison_form = MaisonForm(request.POST)
        if maison_form.is_valid():
            maison_form.save()
            return redirect('maison:liste-maison')
    form = MaisonForm()
    context = {
        "form": form
    }
    return render(request, 'maison/ajouter_maison.html', context)




def supprimer_maison(request, pk):
   try:
       maison = Maison.objects.get(pk=pk)
       maison.delete()

   except Maison.DoesNotExist:
       maison = None

   return redirect('maison:liste-maison')


   def test_func(self):

        if self.request.user.user_type != 3:
            print('Vous n''etes pas autorise ')
            return False

        return True




class Maison_mise_ajour(LoginRequiredMixin, UpdateView):
    model = Maison
    fields = '__all__'
    template_name = 'maison/ajouter_maison.html'

    def get_success_url(self):

        return reverse_lazy('maison:liste-maison')









def detail_maison(request, pk):
        maison =Chambre.objects.filter(maison__id=pk)


        context = {
            'liste_chambre': maison


        }
        return render(request, 'chambre/list_chambre.html', context)











"""
class Maison_mise_ajour(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''
    Mise a jour Maison
    '''
    model = Maison
    form_class = MaisonForm
    success_url = reverse_lazy('list_maison')
    template_name = 'maison/ajouter_maison.html'
    raise_exception = True

    def test_func(self):
        print(' Utilisateur:{0}'.format(self.request.user.user_type))
        if self.request.user.user_type != 2:
            print('Type d''utilisateur refuse, modification non autorisee')
            return False
        return True

    def get_login_url(self):
        if not self.request.user.is_authenticated:
            print('Veuillez vous authentifier')
            return super(Maison_mise_ajour, self).get_login_url()
        return ''

    def get_context_data(self, **kwargs):
        context = super(Maison_mise_ajour, self).get_context_data(**kwargs)
        context['title'] = "Modification de Maison"
        return context


"""




"""
class MaisonView(ListView):
    model = Maison
    template_name = "index.html"



class MaisonDetailView(DetailView):
    model = Maison
    template_name = "maison_detail.html"
"""

templates/maison/ajouter_maison.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">

  <div class="row">


      <div class="col-xl-2 col-md-6 mb-4 ">
    </div>

    <div class="col-xl-8 col-md-6 mb-4">

<h1 class="text-center"> Ajouter Maison</h1>
<form action="." method="post" class="admission-form d-block">
  {% csrf_token %}
  {{ form|crispy }}

  <div class="row">

 <div class="col-xl-8 col-md-6 mb-4 ">
   <a  ><button type="submit"  class="btn btn-primary btn-user btn-block"> <i class=" mdi mdi-database">Enregister</i></button></a>

</div>


<div class="col-xl-4 col-md-6 mb-4 ">
 <a  ><button type="submit"  class="btn btn-danger btn-user btn-block"> <i class=" mdi mdi-cancel">Annuler</i></button></a>

</div>
  </div></form>
</div>

  <div class="col-xl-2 col-md-6 mb-4 ">
</div>
</div>
</div>
{% endblock %}

templates/maison/index.html
{% extends "base.html" %}

{% block content %}


<!-- Begin Page Content -->
<div class="container-fluid">


<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Accueil</h1>
</div>


          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <a href= "{% url 'maison:liste-maison' %}">
                    <div  class="col mr-2">
                      <div  class="text-xs font-weight-bold text-primary text-uppercase mb-1">Maisons</div>
                      <span class="badge badge-dark">{{maisons}}</span>
                    </div>
                    </a>
                    <div class="col-auto">
                      <i class=" fas fa-home  fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <a href= "{% url 'chambre:liste-chambre' %}">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Chambres</div>

                      <span class="badge badge-dark">    {{chambres}}  </span>


                    </div>
                      </a>
                    <div class="col-auto">
                      <i class="fas fa-door-open fa-2x text-gray-300"></i>
                    </div>

                  </div>
                </div>
              </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <a href= "{% url 'contrat:liste-contrat' %}">

                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Locataires</div>
                      <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                        <span class="badge badge-dark">    {{contrats}}  </span>
                        </div>
                        <div class="col">

                        </div>
                      </div>
                    </div>
                    </a>
                    <div class="col-auto">
                      <i class="fas fa-user-friends fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Pending Requests Card Example -->


          <!-- Content Row -->





        <a class="scroll-to-top rounded" href="#page-top">
   <i class="fas fa-angle-up"></i>
 </a>

 <!-- Logout Modal-->
 <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <h5 class="modal-title" id="exampleModalLabel">Vous voulez quittez cette page?</h5>
         <button class="close" type="button" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">×</span>
         </button>
       </div>
       <div class="modal-body">Selectionnez "Se deconnecter" si dessous si vous etes prets a  quitter session.</div>
       <div class="modal-footer">
         <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
         <a class="btn btn-primary" href="{% url 'authentication:login'%}">Se deconnecter</a>
       </div>
     </div>
   </div>
 </div>

 </div>
 </div>


{% endblock content%}

templates/maison/list_locataire.html
    <!-- Start Left menu area -->
    <!-- End Left menu area -->
    <!-- Start Welcome area -->
    <div class="all-content-wrapper">
        <div class="container-fluid">
        </div>
        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap">
                            <h4>Library List</h4>
                            <div class="add-product">
                                <a href="#">Add Library</a>
                            </div>
                            <div class="asset-inner">
                                <table>
                                    <tr>
                                        <th>No</th>
                                        <th>Image</th>
                                        <th>Name of Asset</th>
                                        <th>Status</th>
                                        <th>Subject</th>
                                        <th>Department</th>
                                        <th>Type</th>
                                        <th>Price</th>
                                        <th>Setting</th>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td><img src="img/product/book-1.jpg" alt="" /></td>
                                        <td>Web Development Book</td>
                                        <td>
                                            <button class="pd-setting">Active</button>
                                        </td>
                                        <td>Html, Css</td>
                                        <td>CSE</td>
                                        <td>Book</td>
                                        <td>$1500</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td><img src="img/product/book-2.jpg" alt="" /></td>
                                        <td>Quality Bol pen</td>
                                        <td>
                                            <button class="ps-setting">Paused</button>
                                        </td>
                                        <td>PHP</td>
                                        <td>CSE</td>
                                        <td>CD</td>
                                        <td>$1700</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td><img src="img/product/book-3.jpg" alt="" /></td>
                                        <td>Box of pendrive</td>
                                        <td>
                                            <button class="ds-setting">Disabled</button>
                                        </td>
                                        <td>Java</td>
                                        <td>CSE</td>
                                        <td>Book</td>
                                        <td>$1500</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td><img src="img/product/book-4.jpg" alt="" /></td>
                                        <td>Quality Bol pen</td>
                                        <td>
                                            <button class="pd-setting">Active</button>
                                        </td>
                                        <td>PHP</td>
                                        <td>CSE</td>
                                        <td>CD</td>
                                        <td>$1200</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td><img src="img/product/book-1.jpg" alt="" /></td>
                                        <td>Web Development Book</td>
                                        <td>
                                            <button class="pd-setting">Active</button>
                                        </td>
                                        <td>Wordpress</td>
                                        <td>CSE</td>
                                        <td>Book</td>
                                        <td>$1800</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>6</td>
                                        <td><img src="img/product/book-2.jpg" alt="" /></td>
                                        <td>Quality Bol pen</td>
                                        <td>
                                            <button class="ps-setting">Paused</button>
                                        </td>
                                        <td>Java</td>
                                        <td>CSE</td>
                                        <td>CD</td>
                                        <td>$1000</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="custom-pagination">
								<ul class="pagination">
									<li class="page-item"><a class="page-link" href="#">Previous</a></li>
									<li class="page-item"><a class="page-link" href="#">1</a></li>
									<li class="page-item"><a class="page-link" href="#">2</a></li>
									<li class="page-item"><a class="page-link" href="#">3</a></li>
									<li class="page-item"><a class="page-link" href="#">Next</a></li>
								</ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copyright-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="footer-copy-right">
                            <p>Copyright © 2018. All rights reserved. Template by <a href="https://colorlib.com/wp/templates/">Colorlib</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/maison/list_maison.html
{% extends "base.html" %}

{% block content %}


<!-- Begin Page Content -->
<div class="container-fluid">


<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Liste des Maisons</h1>
{% if user.user_type == 3 %}<a href= "{% url 'maison:ajouter-maison' %}" class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm"><i class="fas fa-data fa-sm text-white-50"></i> Nouvelle Maison</a>{%endif%}
</div>

          <!-- Content Row -->
          <div class="row">

          {% for maison in object_list %}
            <!-- Earnings (Monthly) Card Example -->
            <a href="{% url 'maison:maison-detail'  pk=maison.pk %}">
            <div class="col-xl-4 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="col-auto">
                                          </div>
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><h4>{{maison.nom_maison}}</h4></div>
                      <h5>Nombre de chambre  <span class="counter">{{maison.chambre_set.all.count}}</span> <span class="tuition-fees"></span></h5>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{maisons}}</div>
                    </div>

                    </a>

                        <div class="row">
                          <div class=" col-md-6 ">
                   <a href="{% url 'maison:editMaison' maison.pk  %}"> <button type="button" class="btn btn-info  btn-edit">

                    <i class="mdi mdi-file-check btn-icon-append">   Editer</i>
                    </button></a>
                    </div>


                    <div class=" col-md-6 ">

                 <a href="{% url 'maison:supprimer-maison' pk=maison.pk %}" > <button type="button" class="btn btn-danger  btn-sup">

                    <i class="mdi mdi-delete btn-icon-append">  Supprimer</i>
                    </button></a>
                      </div>
                    </div>






                  </div>
                </div>
              </div>
            </div>



            {% endfor%}

 </div>
        <a class="scroll-to-top rounded" href="#page-top">
   <i class="fas fa-angle-up"></i>
 </a>

 <!-- Logout Modal-->
 <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <h5 class="modal-title" id="exampleModalLabel">Vous voulez quittez cette page?</h5>
         <button class="close" type="button" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">×</span>
         </button>
       </div>
       <div class="modal-body">Selectionnez "Se deconnecter" si dessous si vous etes prets a  quitter session.</div>
       <div class="modal-footer">
         <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
         <a class="btn btn-primary" href="{% url 'authentication:login'%}">Se deconnecter</a>
       </div>
     </div>
   </div>
 </div>


{% endblock content%}

templates/maison/modifier_maison.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section id="update-student">
  <div id="update-student-inner">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8 py-5">
          <div id="student-update-form">
            <form class="sudent-update-form" action="." method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <a href="{% url '' %}" class="btn btn-dark">
                <i class="fas fa-arrow-left"></i> Back
              </a>
              <input class="btn btn-info" type="submit" value="Update Details">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}