authentication/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import  SignUp , login_view,logout

app_name ="authentication"

urlpatterns = [

path('signup/', SignUp.as_view(), name='signup'),
path('login/', login_view, name='login'),
path('logout/', logout, name='logout'),





]

# for adding media file settings
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chambre/urls.py
from django.urls import path
from .views import  (chambre ,liste_chambre, supprimer_chambre, Chambre_mise_ajour,search)

app_name="chambre"

urlpatterns = [

    path('ajouter-chambre/', chambre , name='ajouter-chambre'),
    path('liste-chambre/', liste_chambre , name='liste-chambre'),
    path('<int:pk>/delete_chambre/', supprimer_chambre, name='supprimer-chambre'),
    path('editchambre/<int:pk>/', Chambre_mise_ajour.as_view(), name='editchambre'),
    path('search/', search , name='search'),



    ]

contrat/urls.py
from django.urls import path
from .views import *

app_name="contrat"

urlpatterns = [

    path('ajouter-contrat/', contrat , name='ajouter-contrat'),
    path('liste-contrat/', list_contrat , name='liste-contrat'),
    path('<int:pk>/supprimer-contrat/', supprimer_contrat, name='supprimer-contrat'),
    path('<int:pk>/modifier-contrat/', Contrat_mise_ajour.as_view(), name='modifier-contrat'),
    path('locataire-info/', ajouter_locataire_info , name='locataire-info'),
    path('locataire-detail/<int:locataire_id>/',detail_locataire , name='locataire-detail'),
    path('<int:pk>/delete-info/', supprimer_info, name='supprimer-info'),
    path('editinfo/<int:pk>/', Info_mise_ajour.as_view(), name='editinfo'),
    path('search-locataire/', search_maison , name='search-locataire'),




    ]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import HomeView,\
    ItemDetailView,\
    CheckoutView,\
    add_to_cart,\
    remove_from_cart,\
    OrderSummaryView,\
    remove_single_item_from_cart,\
    PaymentMethod,\
    AddCouponView,\
    CategoryListView,\
    RequestRefundView,\
    ProfileView,\
    product
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<category>', CategoryListView.as_view(), name='category-list'),
    path('product/<slug:slug>', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/<slug:slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug:slug>', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='check-out'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>', PaymentMethod.as_view(), name='payment'),
    path('payment/<payment_option>', PaymentMethod.as_view(), name='payment'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('request-refund/<str:ref_code>', RequestRefundView.as_view(), name='request-refund'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

# for adding media file settings
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

houseProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('maison.urls')),
    path('index/', include('chambre.urls')),
    path('index/', include('contrat.urls')),
    path('index/', include('payement.urls')),
    path('index/', include('payement_e_e.urls')),
    path('', include('authentication.urls')),
    path('', include('django.contrib.auth.urls')),




    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chambre/models.py
from django.db import models
from maison.models import Maison




STATUS_CHOICES = (
    ('L', 'Libre'),
    ('O', 'Occupee'),
    ('I', 'Indisponible')


)

class Chambre(models.Model):
     type_chambre = models.CharField(max_length=50, null=True, blank=True)
     maison = models.ForeignKey(Maison, on_delete=models.CASCADE, editable=True)
     nom = models.CharField(max_length=25)
     prix = models.FloatField()
     statut = models.CharField(choices=STATUS_CHOICES, max_length=1)




     class Meta:
        ordering = ['nom' ]
        permissions = (('peut voir chamnbre', 'Peut voir chambre'),('peut voir detail chamnbre', 'Peut voir  detail chambre'))

     def get_absolute_url(self):
        return reverse('chambre-detail', args=str([self.pk]))

     def __str__(self):
        return   '{0}'.format( self.nom)

     def is_statut(self):
         if self.statut =='L':
             return True
         return False

chambre/forms.py
from  django import forms
from .models import  *
from chambre.models import Chambre

class ChambreForm(forms.ModelForm):
   class Meta:

      model = Chambre
      fields = ('type_chambre', 'nom','prix','statut','maison')
      labels={
          'type_chambre':'Type de chambre',
          'nom':'Nom de la chambre',
          'prix':'Prix',
          'statut':'Statut',
          'maison':'Maison'
      }




class ChambreForm(forms.Form):




            STATUS_CHOICES = (
            ('L', 'Libre'),
            ('O', 'Occupee'),
            ('I', 'Indisponible')


            )


            maison =forms.ModelChoiceField(queryset=Maison.objects.all(), empty_label=None, label='Maison')
            statut = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect(), help_text='Pardon Selectionnez le statut de la chambre:', initial='1')

            nom= forms.CharField(
            label='Nom',
            widget=forms.TextInput(attrs={'placeholder': 'Nom'})

            )
            prix= forms.FloatField(
            label='Prix',
            widget=forms.TextInput(attrs={'placeholder': 'Prix'})
            )

            type_chambre= forms.CharField(
            label="Type de chambre",
            widget=forms.TextInput(attrs={'placeholder': 'Type de chambre'})
            )



            """
            def clean_chambre(self):
                cleaned_data= super(ChambreForm,self).clean()
                chambre = cleaned_data.get('chambre')
                maison =cleaned_data.get('maison')



                if chambre and maison:
                   chambre = [chambre,maison]
                   rep=''.join(chambre)
                return rep
             """

chambre/views.py
from django.views.generic import (CreateView, DeleteView, ListView, FormView, UpdateView, ListView, DetailView)
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User, Group
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError
from django.db import transaction, IntegrityError
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import render
from django.views import generic
from django.views.generic import ListView, DetailView #Signup, ReservationForm, CheckInRequestForm
from .forms import ChambreForm
from .models import Chambre, Maison
# Create your views here.

#@login_required

def liste_chambre(request):
    if request.method == 'GET':
        liste_chambres = Chambre.objects.all()
        liste_maisons = Maison.objects.all()
        context = {
            "liste_chambre": liste_chambres,
            "liste_maison": liste_maisons,
        }
    return render(request, 'chambre/list_chambre.html', context)


def chambre(request):

    msg=None
    form = ChambreForm()
    if request.method == 'POST':
        form = ChambreForm(request.POST)
        if form.is_valid():
            nom = form.cleaned_data['nom']
            type_chambre = form.cleaned_data['type_chambre']
            maison = form.cleaned_data['maison']
            statut = form.cleaned_data['statut']
            prix = form.cleaned_data['prix']


            qs=Chambre.objects.filter(maison=maison,nom=nom )
            if qs.exists():
                msg='Cette chambre existe deja dans cette maison'
            else:


                instance = Chambre(
                    nom =nom,
                    type_chambre=type_chambre,
                    maison=maison,
                    statut=statut,
                    prix=prix,

                    )
                instance.save()

                return redirect('chambre:liste-chambre')

    else:
        form = ChambreForm()

    context = {
        'form': form,
        'msg':msg,

    }
    return render(request, 'chambre/ajouter_chambre.html', context)



def supprimer_chambre(request, pk):
   try:
       chambre = Chambre.objects.get(pk=pk)
       chambre.delete()

   except Chambre.DoesNotExist:
       chambre = None

   return redirect('chambre:liste-chambre')





class Chambre_mise_ajour(LoginRequiredMixin, UpdateView):
    model = Chambre
    fields = '__all__'
    template_name = 'chambre/ajouter_chambre.html'

    def get_success_url(self):

        return reverse_lazy('chambre:liste-chambre')





def search(request):
        query = request.GET.get('query')
        if not query:
            chambre = Chambre.objects.all()
        else:
            # title contains the query is and query is not sensitive to case.

            chambre =Chambre.objects.all().filter(maison__nom_maison__icontains=query)

        context = {
            'liste_chambre': chambre,

        }
        return render(request, 'chambre/list_chambre.html', context)

templates/chambre/ajouter_chambre.html
<!-- templates/lecturer/course.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags%}
 {% block content %} <!-- Add Department Modal -->

 <div class="container-fluid">

   <div class="row">

       <div class="col-xl-2 col-md-6 mb-4 ">
     </div>

     <div class="col-xl-8 col-md-6 mb-4 ">


 <h1 class="text-center">Ajouter Chambre</h1>



 <form action="." method="post" class="admission-form d-block center">
   {% csrf_token %}
     {% if msg %}
     {{msg}}
       {% else %}
   {{ form.maison|as_crispy_field }}
   {{ form.nom|as_crispy_field }}
   {{ form.type_chambre|as_crispy_field }}
   {{ form.prix|as_crispy_field }}
   {{ form.statut|as_crispy_field }}
     {% endif %}
   <div class="row">

  <div class="col-xl-8 col-md-6 mb-4 ">
    <a  ><button type="submit"  class="btn btn-primary btn-user btn-block"> <i class=" mdi mdi-database">Enregister</i></button></a>

</div>


<div class="col-xl-4 col-md-6 mb-4 ">
  <a  ><button type="submit"  class="btn btn-danger btn-user btn-block"> <i class=" mdi mdi-cancel">Annuler</i></button></a>

</div>
   </div>
 </form>
  </div>



    <div class="col-xl-2 col-md-6 mb-4 ">
  </div>

  </div>
   </div>




 {%endblock%}

templates/chambre/ajouter_contrat.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
 <div class="container-fluid">
   <div class="row">
     <div class="col-xl-2 col-md-6 mb-4 ">
   </div>

  <div class="col-xl-8 col-md-6 mb-4 ">
  <form method="post">
    {% csrf_token %}



          {{ form.nom_locataire|as_crispy_field }}

          {{ form.prenom_locataire|as_crispy_field }}
          {{ form.sexe|as_crispy_field }}
          {{ form.contact_no|as_crispy_field }}
            {{ form.address|as_crispy_field }}
              {{ form.email_address|as_crispy_field }}
           {{ form.maison|as_crispy_field }}
             {{ form.chambre|as_crispy_field }}
         {{ form.caution|as_crispy_field }}





    <div class="form-row">
      <div class="form-group col-md-4 mb-0">
        {{ form.date_contrat|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.date_entree|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.date_sortie|as_crispy_field }}
      </div>

    </div>

    <div class="row">

   <div class="col-xl-8 col-md-6 mb-4 ">
     <a  ><button type="submit"  class="btn btn-primary btn-user btn-block"> <i class=" mdi mdi-database">Enregister</i></button></a>

  </div>


  <div class="col-xl-4 col-md-6 mb-4 ">
   <a  ><button type="submit"  class="btn btn-danger btn-user btn-block"> <i class=" mdi mdi-cancel">Annuler</i></button></a>

  </div>
    </div>

  </form>
    </div>

  <div class="col-xl-2 col-md-6 mb-4 ">
</div>
</div>
</div>



{% endblock %}

templates/chambre/list_chambre.html
{% extends "base.html" %}

{% block content %}

            <div class="container-fluid">



              <style type="text/css">

              .table-wrapper {
                  background: #fff;
                  padding: 20px 25px;
                  margin: 30px 0;
              border-radius: 3px;
                  box-shadow: 0 1px 1px rgba(0,0,0,.05);
              }
              .table-title {
              padding-bottom: 15px;
              background: #4e73df;;
              color: #fff;
              padding: 16px 30px;
              margin: -20px -25px 10px;
              border-radius: 3px 3px 0 0;
              }
              .table-title h2 {
              margin: 5px 0 0;
              font-size: 24px;
              }
              .table-title .btn {
              color: #566787;
              float: right;
              font-size: 13px;
              background: #fff;
              border: none;
              min-width: 50px;
              border-radius: 2px;
              border: none;
              outline: none !important;
              margin-left: 10px;
              }
              .table-title .btn:hover, .table-title .btn:focus {
                  color: #566787;
              background: #f2f2f2;
              }
              .table-title .btn i {
              float: left;
              font-size: 21px;
              margin-right: 5px;
              }
              .table-title .btn span {
              float: left;
              margin-top: 2px;
              }
              table.table tr th, table.table tr td {
                  border-color: #e9e9e9;
              padding: 12px 15px;
              vertical-align: middle;
              }
              table.table tr th:first-child {
              width: 60px;
              }
              table.table tr th:last-child {
              width: 100px;
              }
              table.table-striped tbody tr:nth-of-type(odd) {
                background-color: #fcfcfc;
              }
              table.table-striped.table-hover tbody tr:hover {
              background: #f5f5f5;
              }
              table.table th i {
                  font-size: 13px;
                  margin: 0 5px;
                  cursor: pointer;
              }
              table.table td:last-child i {
              opacity: 0.9;
              font-size: 22px;
                  margin: 0 5px;
              }
              table.table td a {
              font-weight: bold;
              color: #566787;
              display: inline-block;
              text-decoration: none;
              }
              table.table td a:hover {
              color: #2196F3;
              }
              table.table td a.settings {
                  color: #2196F3;
              }
              table.table td a.delete {
                  color: #F44336;
              }
              table.table td i {
                  font-size: 19px;
              }
              table.table .avatar {
              border-radius: 50%;
              vertical-align: middle;
              margin-right: 10px;
              }
              .status {
              font-size: 30px;
              margin: 2px 2px 0 0;
              display: inline-block;
              vertical-align: middle;
              line-height: 10px;
              }
              .text-success {
                  color: #10c469;
              }
              .text-info {
                  color: #62c9e8;
              }
              .text-warning {
                  color: #FFC107;
              }
              .text-danger {
                  color: #ff5b5b;
              }
              .pagination {
                  float: right;
                  margin: 0 0 5px;
              }
              .pagination li a {
                  border: none;
                  font-size: 13px;
                  min-width: 30px;
                  min-height: 30px;
                  color: #999;
                  margin: 0 2px;
                  line-height: 30px;
                  border-radius: 2px !important;
                  text-align: center;
                  padding: 0 6px;
              }
              .pagination li a:hover {
                  color: #666;
              }
              .pagination li.active a, .pagination li.active a.page-link {
                  background: #03A9F4;
              }
              .pagination li.active a:hover {
                  background: #0397d6;
              }
              .pagination li.disabled i {
                  color: #ccc;
              }
              .pagination li i {
                  font-size: 16px;
                  padding-top: 6px
              }
              .hint-text {
                  float: left;
                  margin-top: 10px;
                  font-size: 13px;
              }


              </style>


        <script type="text/javascript">
        $(document).ready(function(){
        	$('[data-toggle="tooltip"]').tooltip();
        });
        </script>



      <div class="row">

          <div class="col-xl-12 col-md-12 mb-12 ">


            <div  class=" shadow ">
                <div class="table-wrapper ">
                    <div class="table-title  ">
                        <div class="row">
                            <div class="col-sm-5">

        					</div>
        					<div class="col-sm-7">
        						<a href="{% url 'chambre:ajouter-chambre' %}" <button type="button" name="button" class="float-right btn btn-secondary"><i class=" mdi mdi-plus-circle  "></i></button> <span>Nouvelle Chambre</span></a>

                      	</div>



                        </div>
                    </div>



                    <div class="table-filter">
				<div class="row">
                    <div class="col-sm-4">

					</div>
                    <div class="col-sm-4">
                      <!-- Topbar Search -->
                      <form class=" d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"    action="{% url 'chambre:search'  %}" method="get" accept-charset="utf-8">
                        <div class="input-group">
                          <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="query">
                          <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                              <i class="fas fa-search fa-sm"></i>
                            </button>
                          </div>
                        </div>
                      </form>

                    </div>

                    <div class="col-sm-4">

					</div>
                </div>
			</div>
                    <table class="table table-striped table-hover">
                        <thead>

                            <tr>
                                <th>#</th>
                                <th>NOM DE LA CHAMBRE</th>
        						            <th>TYPE DE CHAMBRE</th>
        						             <th>PRIX</th>
                                 <th>STATUT</th>
                                 <th>MAISON</th>
                                 <th>ACTION</th>
                            </tr>

                        </thead>
                        <tbody>
                          {%  for chambre in liste_chambre %}
                            <tr>
                                <td>{{chambre.id}}</td>
                                <td>{{chambre.nom}}</td>
                                <td>{{chambre.type_chambre}}</td>
                                <td>{{chambre.prix}}</td>

                  {% if chambre.is_statut %} <td><label class="badge badge-success">{{chambre.get_statut_display}}</label></td>  <td>{{chambre.maison}}</td> {%else%}<td><label class="badge badge-danger">{{chambre.get_statut_display}}</label></td>
                    <td>{{chambre.maison}}</td>  {%endif%}
        						<td>
        							<a href="{% url 'chambre:editchambre' pk=chambre.pk %}" class="settings" title="Settings" data-toggle="tooltip"><i class=" mdi mdi-pencil  "></i></a>
        					<a  href="{% url 'chambre:supprimer-chambre' pk=chambre.pk %}" ><i class=" mdi mdi-delete contrat-i  "></i></a>
        						</td>
                            </tr>

                            {%endfor%}



                        </tbody>
                    </table>
                    <div class="clearfix">
                              <div class="hint-text">Montrant <strong>5</strong> sorties de <strong>25</strong> entrees</div>
                              <ul class="pagination">
                                  <li class="page-item disabled"><a href="#">Precedent</a></li>
                                  <li class="page-item"><a href="#" class="page-link">1</a></li>
                                  <li class="page-item"><a href="#" class="page-link">2</a></li>
                                  <li class="page-item active"><a href="#" class="page-link">3</a></li>
                                  <li class="page-item"><a href="#" class="page-link">4</a></li>
                                  <li class="page-item"><a href="#" class="page-link">5</a></li>
                                  <li class="page-item"><a href="#" class="page-link">Suivant</a></li>
                              </ul>
                          </div>
                </div>
            </div>

        </div >
         </div >


         <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
           <div class="modal-dialog" role="document">
             <div class="modal-content">
               <div class="modal-header">
                 <h5 class="modal-title" id="exampleModalLabel">Vous voulez quittez cette page?</h5>
                 <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">×</span>
                 </button>
               </div>
               <div class="modal-body">Selectionnez "Se deconnecter" si dessous si vous etes prets a  quitter session.</div>
               <div class="modal-footer">
                 <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                 <a class="btn btn-primary" href="{% url 'authentication:login'%}">Se deconnecter</a>
               </div>
             </div>
           </div>
         </div>
          </div >




























{% endblock content %}

templates/chambre/list_contrat.html
{% extends "base.html" %}

{% block content %}



<div class=" card-body">

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
      <h4 class="card-title">Liste des contrats</h4>
    <a href="{%url 'contrat:ajouter-contrat'%}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="mdi mdi-plus mdi-sm text-white-50"></i> Nouveau Contrat</a>
  </div>



                  <div class="table-responsive pt-3">
                    <div class="card">


                    <table class="table table-dark">
                      <thead>

                        <tr>
                          <th>
                            #
                          </th>
                          <th>
                            Nom
                          </th>
                          <th>
                            Prenoms
                          </th>
                          <th>
                            Maison
                          </th>
                          <th>
                            Chambre
                          </th>
                          <th>
                            Date du contrat
                          </th>
                          <th>
                            Date d'entree
                          </th>
                          <th>
                            Date de sortie
                          </th>
                          <th>
                            Action
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                            {% for contrat in contrat%}
                        <tr>
                          <td>
                            1
                          </td>
                          <td>
                            {{contrat.locataire.nom_locataire}}
                          </td>
                          <td>
                            {{contrat.locataire.prenom_locataire}}
                          </td>
                          <td>
                            {{contrat.maison}}
                          </td>
                          <td>
                            {{contrat.chambre}}
                          </td>
                          <td>
                            {{contrat.date_contrat}}
                          </td>
                          <td>
                            {{contrat.date_entree}}
                          </td>
                          <td>
                            {{contrat.date_sortie}}
                          </td>
                          <td>
                            <a href="{% url 'contrat:modifier-contrat' pk=contrat.pk %}" class="settings contrat-i" title="Settings" data-toggle="tooltip"><i class=" mdi mdi-pencil   "></i></a>
                            <a href="{% url 'contrat:supprimer-contrat' pk=contrat.pk %}" ><i class=" mdi mdi-delete contrat-i "></i></a>
                          </td>
                        </tr>

                    {%endfor%}
                      </tbody>
                    </table>
                      </div>
                  </div>
                </div>
                {% endblock content%}

templates/chambre/search.html
{% extends 'base.html' %}

{% block content %}

    {% include 'chambre/list_chambre.html'  %}

{% endblock %}