chambre/urls.py
from django.urls import path
from .views import  (chambre ,liste_chambre, supprimer_chambre, Chambre_mise_ajour,search)

app_name="chambre"

urlpatterns = [

    path('ajouter-chambre/', chambre , name='ajouter-chambre'),
    path('liste-chambre/', liste_chambre , name='liste-chambre'),
    path('<int:pk>/delete_chambre/', supprimer_chambre, name='supprimer-chambre'),
    path('editchambre/<int:pk>/', Chambre_mise_ajour.as_view(), name='editchambre'),
    path('search/', search , name='search'),



    ]

contrat/urls.py
from django.urls import path
from .views import *

app_name="contrat"

urlpatterns = [

    path('ajouter-contrat/', contrat , name='ajouter-contrat'),
    path('liste-contrat/', list_contrat , name='liste-contrat'),
    path('<int:pk>/supprimer-contrat/', supprimer_contrat, name='supprimer-contrat'),
    path('<int:pk>/modifier-contrat/', Contrat_mise_ajour.as_view(), name='modifier-contrat'),
    path('locataire-info/', ajouter_locataire_info , name='locataire-info'),
    path('locataire-detail/<int:locataire_id>/',detail_locataire , name='locataire-detail'),
    path('<int:pk>/delete-info/', supprimer_info, name='supprimer-info'),
    path('editinfo/<int:pk>/', Info_mise_ajour.as_view(), name='editinfo'),
    path('search-locataire/', search_maison , name='search-locataire'),




    ]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import HomeView,\
    ItemDetailView,\
    CheckoutView,\
    add_to_cart,\
    remove_from_cart,\
    OrderSummaryView,\
    remove_single_item_from_cart,\
    PaymentMethod,\
    AddCouponView,\
    CategoryListView,\
    RequestRefundView,\
    ProfileView,\
    product
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<category>', CategoryListView.as_view(), name='category-list'),
    path('product/<slug:slug>', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/<slug:slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug:slug>', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='check-out'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>', PaymentMethod.as_view(), name='payment'),
    path('payment/<payment_option>', PaymentMethod.as_view(), name='payment'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('request-refund/<str:ref_code>', RequestRefundView.as_view(), name='request-refund'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

# for adding media file settings
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

houseProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('maison.urls')),
    path('index/', include('chambre.urls')),
    path('index/', include('contrat.urls')),
    path('index/', include('payement.urls')),
    path('index/', include('payement_e_e.urls')),
    path('', include('authentication.urls')),
    path('', include('django.contrib.auth.urls')),




    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

maison/urls.py
from django.urls import path
from .views import  index,List_maison,maison,supprimer_maison, Maison_mise_ajour,detail_maison

app_name ="maison"

urlpatterns = [
path('', index , name='index'),
#path('maison-detail/<slug>/', MaisonDetailView.as_view(), name='maison-detail'),
path('liste-maison/', List_maison.as_view() , name='liste-maison'),
path('ajouter-maison/', maison , name='ajouter-maison'),
path('<int:pk>/delete/', supprimer_maison, name='supprimer-maison'),
path('editMaison/<int:pk>/', Maison_mise_ajour.as_view(), name='editMaison'),
path('maison-detail/<int:pk>/',detail_maison , name='maison-detail'),
]

payement/urls.py
from django.urls import path
from .views import *

app_name="payement"

urlpatterns = [

    path('ajouter-payement/', payement , name='ajouter-payement'),
    path('liste-payement/', list_payement , name='liste-payement'),
    path('<int:pk>/supprimer-payement/', supprimer_payement, name='supprimer-payement'),
    path('<int:pk>/modifier-payement/', Payement_mise_ajour.as_view(), name='modifier-payement'),
    path('search-annee/', search_annee , name='search-annee'),



    ]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>


{% include "header.html" %}


</head>
 <body id="page-top">
    <div id="wrapper">


    {% include "sidebar.html" %}
    <div id="content-wrapper" class="d-flex flex-column">

     <div id="content">
      {% include "navbar.html" %}

    {% block content %}

    {% endblock content %}

</div>
    {% include "footer.html" %}
</div>


  </div>

    {% include "scripts.html" %}
</body>
</html>

templates/footer.html
{% if user.is_authenticated %}
<footer class="sticky-footer bg-white">
       <div class="container my-auto">
         <div class="copyright text-center my-auto">
           <span>Copyright &copy; Your Website 2020</span>
         </div>
       </div>
     </footer>
  {%endif%}   

templates/header.html
{% load static %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>House Location</title>

<!-- Custom fonts for this template-->
<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
 <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}">
<!-- Custom styles for this template-->
<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
<link href="{% static 'css/customer.css' %}" rel="stylesheet">
<!-- Custom styles for this page -->
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
<link href="{% static  'css/datepicker.css' %}">

templates/list_locataire.html
    <!-- Start Left menu area -->
    <!-- End Left menu area -->
    <!-- Start Welcome area -->
    <div class="all-content-wrapper">
        <div class="container-fluid">
        </div>
        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap">
                            <h4>Library List</h4>
                            <div class="add-product">
                                <a href="#">Add Library</a>
                            </div>
                            <div class="asset-inner">
                                <table>
                                    <tr>
                                        <th>No</th>
                                        <th>Image</th>
                                        <th>Name of Asset</th>
                                        <th>Status</th>
                                        <th>Subject</th>
                                        <th>Department</th>
                                        <th>Type</th>
                                        <th>Price</th>
                                        <th>Setting</th>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td><img src="img/product/book-1.jpg" alt="" /></td>
                                        <td>Web Development Book</td>
                                        <td>
                                            <button class="pd-setting">Active</button>
                                        </td>
                                        <td>Html, Css</td>
                                        <td>CSE</td>
                                        <td>Book</td>
                                        <td>$1500</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td><img src="img/product/book-2.jpg" alt="" /></td>
                                        <td>Quality Bol pen</td>
                                        <td>
                                            <button class="ps-setting">Paused</button>
                                        </td>
                                        <td>PHP</td>
                                        <td>CSE</td>
                                        <td>CD</td>
                                        <td>$1700</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td><img src="img/product/book-3.jpg" alt="" /></td>
                                        <td>Box of pendrive</td>
                                        <td>
                                            <button class="ds-setting">Disabled</button>
                                        </td>
                                        <td>Java</td>
                                        <td>CSE</td>
                                        <td>Book</td>
                                        <td>$1500</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td><img src="img/product/book-4.jpg" alt="" /></td>
                                        <td>Quality Bol pen</td>
                                        <td>
                                            <button class="pd-setting">Active</button>
                                        </td>
                                        <td>PHP</td>
                                        <td>CSE</td>
                                        <td>CD</td>
                                        <td>$1200</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td><img src="img/product/book-1.jpg" alt="" /></td>
                                        <td>Web Development Book</td>
                                        <td>
                                            <button class="pd-setting">Active</button>
                                        </td>
                                        <td>Wordpress</td>
                                        <td>CSE</td>
                                        <td>Book</td>
                                        <td>$1800</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>6</td>
                                        <td><img src="img/product/book-2.jpg" alt="" /></td>
                                        <td>Quality Bol pen</td>
                                        <td>
                                            <button class="ps-setting">Paused</button>
                                        </td>
                                        <td>Java</td>
                                        <td>CSE</td>
                                        <td>CD</td>
                                        <td>$1000</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="custom-pagination">
								<ul class="pagination">
									<li class="page-item"><a class="page-link" href="#">Previous</a></li>
									<li class="page-item"><a class="page-link" href="#">1</a></li>
									<li class="page-item"><a class="page-link" href="#">2</a></li>
									<li class="page-item"><a class="page-link" href="#">3</a></li>
									<li class="page-item"><a class="page-link" href="#">Next</a></li>
								</ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copyright-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="footer-copy-right">
                            <p>Copyright © 2018. All rights reserved. Template by <a href="https://colorlib.com/wp/templates/">Colorlib</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/navbar.html
<!-- Topbar -->
 {% if request.user.is_authenticated %}
       <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

         <!-- Sidebar Toggle (Topbar) -->
         <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
           <i class="fa fa-bars"></i>
         </button>

         <!-- Topbar Search -->
         <form class=" d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"    action="{% url 'chambre:search'  %}" method="get" accept-charset="utf-8">
           <div class="input-group">
             <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="query">
             <div class="input-group-append">
               <button class="btn btn-primary" type="button">
                 <i class="fas fa-search fa-sm"></i>
               </button>
             </div>
           </div>
         </form>

         <!-- Topbar Navbar -->
         <ul class="navbar-nav ml-auto">

           <!-- Nav Item - Search Dropdown (Visible Only XS) -->
           <li class="nav-item dropdown no-arrow d-sm-none">
             <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fas fa-search fa-fw"></i>
             </a>
             <!-- Dropdown - Messages -->
             <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
               <form class="form-inline mr-auto w-100 navbar-search">
                 <div class="input-group">
                   <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="query">
                   <div class="input-group-append">
                     <button class="btn btn-primary" type="button">
                       <i class="fas fa-search fa-sm"></i>
                     </button>
                   </div>
                 </div>
               </form>
             </div>
           </li>

           <!-- Nav Item - Alerts -->
           <li class="nav-item dropdown no-arrow mx-1">
             <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fas fa-bell fa-fw"> <span class="badge badge-danger badge-counter">  {{num_visits}}  </span></i>
               <!-- Counter - Alerts -->

             </a>
             <!-- Dropdown - Alerts -->
             <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
               <h6 class="dropdown-header">
                 Alerts Center
               </h6>
               <a class="dropdown-item d-flex align-items-center" href="#">
                 <div class="mr-3">
                   <div class="icon-circle bg-primary">
                     <i class="fas fa-file-alt text-white"></i>
                   </div>
                 </div>
                 <div>
                   <div class="small text-gray-500">December 12, 2019</div>
                   <span class="font-weight-bold">A new monthly report is ready to download!</span>
                 </div>
               </a>
               <a class="dropdown-item d-flex align-items-center" href="#">
                 <div class="mr-3">
                   <div class="icon-circle bg-success">
                     <i class="fas fa-donate text-white"></i>
                   </div>
                 </div>
                 <div>
                   <div class="small text-gray-500">December 7, 2019</div>
                   $290.29 has been deposited into your account!
                 </div>
               </a>
               <a class="dropdown-item d-flex align-items-center" href="#">
                 <div class="mr-3">
                   <div class="icon-circle bg-warning">
                     <i class="fas fa-exclamation-triangle text-white"></i>
                   </div>
                 </div>
                 <div>
                   <div class="small text-gray-500">December 2, 2019</div>
                   Spending Alert: We've noticed unusually high spending for your account.
                 </div>
               </a>
               <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
             </div>
           </li>



           <!-- Nav Item - Messages -->
           <li class="nav-item dropdown no-arrow mx-1">
             <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <i class="fas fa-envelope fa-fw"></i>
               <!-- Counter - Messages -->
               <span class="badge badge-danger badge-counter">44</span>
             </a>
             <!-- Dropdown - Messages -->
             <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
               <h6 class="dropdown-header">
                 Message Center
               </h6>
               <a class="dropdown-item d-flex align-items-center" href="#">
                 <div class="dropdown-list-image mr-3">
                   <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                   <div class="status-indicator bg-success"></div>
                 </div>
                 <div class="font-weight-bold">
                   <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                   <div class="small text-gray-500">Emily Fowler · 58m</div>
                 </div>
               </a>
               <a class="dropdown-item d-flex align-items-center" href="#">
                 <div class="dropdown-list-image mr-3">
                   <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                   <div class="status-indicator"></div>
                 </div>
                 <div>
                   <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                   <div class="small text-gray-500">Jae Chun · 1d</div>
                 </div>
               </a>
               <a class="dropdown-item d-flex align-items-center" href="#">
                 <div class="dropdown-list-image mr-3">
                   <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                   <div class="status-indicator bg-warning"></div>
                 </div>
                 <div>
                   <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                   <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                 </div>
               </a>
               <a class="dropdown-item d-flex align-items-center" href="#">
                 <div class="dropdown-list-image mr-3">
                   <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                   <div class="status-indicator bg-success"></div>
                 </div>
                 <div>
                   <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                   <div class="small text-gray-500">Chicken the Dog · 2w</div>
                 </div>
               </a>
               <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
             </div>
           </li>



             <!--Nav item login, logout and signup -->
             {% if request.user.is_authenticated %}
         <li class="nav-item">
           <a class="nav-link waves-effect" href="{% url 'authentication:login' %}">
             <span class="clearfix d-none d-sm-inline-block"> Deconnexion </span>
           </a>
         </li>
         {% else %}
         <li class="nav-item">
           <a class="nav-link waves-effect" href="{% url 'authentication:login' %}">
             <span class="clearfix d-none d-sm-inline-block"> Login </span>
           </a>
         </li>
         <li class="nav-item">
           <a class="nav-link waves-effect" href="">
             <span class="clearfix d-none d-sm-inline-block"> Signup </span>
           </a>
         </li>
         {% endif %}

           <div class="topbar-divider d-none d-sm-block"></div>

           <!-- Nav Item - User Information -->
           <li class="nav-item dropdown no-arrow">
             <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username}}</span>
                                                             {%if user.profile_image%}
               <img class="img-profile rounded-circle" src="{{ user.profile_image.url }}">
                                                                {%endif%}
             </a>
             <!-- Dropdown - User Information -->
             <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
               <a class="dropdown-item" href="#">
                 <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                 Profile
               </a>
               <a class="dropdown-item" href="#">
                 <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                 Settings
               </a>
               <a class="dropdown-item" href="#">
                 <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                 Activity Log
               </a>
               <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="{% url 'authentication:login' %}" data-toggle="modal" data-target="#logoutModal">
                 <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                 Se deconnecter
               </a>
             </div>
           </li>

         </ul>

       </nav>
       {%endif%}
       <!-- End of Topbar -->

templates/sidebar.html
<!-- Sidebar -->
     {%load static%}
     {% if request.user.is_authenticated  %}
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon ">
            <i class="fas fa-home fa-3x"></i>

        </div>

        <div class="sidebar-brand-text mx-3">GL</div>

      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      {% if user.user_type == 3%}
      <div class="icones">


      <li class="nav-item active">
        <a class="nav-link" href="{% url 'maison:index'%}">
          <i class="mdi mdi-file-document-box menu-icon"></i>
          <span>Accueil</span></a>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Habitats
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class=" fas fa-home "></i>
          <span>MAISON</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gestion des maisons:</h6>
            <a class="collapse-item" href="{% url 'maison:liste-maison'%}">Liste des maisons</a>
            <a class="collapse-item" href="{% url 'maison:ajouter-maison'%}">Ajouter maison</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class=" fa fa-door-open"></i>
          <span>CHAMBRE</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gestion des chambres:</h6>
            <a class="collapse-item" href="{%url 'chambre:liste-chambre'%}">Liste des chambres</a>
            <a class="collapse-item" href="{%url 'chambre:ajouter-chambre'%}">Ajouter chambre</a>

          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Personnes
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="  fa fa-user"></i>
          <span>Locataires</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gestion des Locataires</h6>
            <a class="collapse-item" href="{%url 'contrat:liste-contrat'%}">Liste des Locataires</a>
            <a class="collapse-item" href="{%url 'contrat:ajouter-contrat'%}">Ajouter Locataire</a>
            <a class="collapse-item" href="{%url 'contrat:locataire-info'%}">Ajouter Information</a>

          </div>
        </div>
        </li>




      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{%url 'payement:liste-payement'%}">
          <i class=" fas fa-money-check " ></i>
          <span>Payement Loyer</span></a>
      </li
          <hr class="sidebar-divider">
      <li class="nav-item">
        <a class="nav-link" href="{%url 'payement_e_e:liste-payement_e_e'%}">
          <i class=" fas fa-money-check " ></i>
          <span>Payement Eau/Ele</span></a>
      </li>









        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
          Autres
        </div>


      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:signup' %}">
          <i class=" fas fa-user-plus  " ></i>
          <span>Enregistrement</span></a>
      </li>



      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:login' %}">
          <i class=" fas fa-sign-out-alt " ></i>
          <span>Deconnexion</span></a>
      </li>


        </div>
        {%endif%}

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    {% endif %}
    <!-- End of Sidebar -->