authentication/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import  SignUp , login_view,logout

app_name ="authentication"

urlpatterns = [

path('signup/', SignUp.as_view(), name='signup'),
path('login/', login_view, name='login'),
path('logout/', logout, name='logout'),





]

# for adding media file settings
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

contrat/urls.py
from django.urls import path
from .views import *

app_name="contrat"

urlpatterns = [

    path('ajouter-contrat/', contrat , name='ajouter-contrat'),
    path('liste-contrat/', list_contrat , name='liste-contrat'),
    path('<int:pk>/supprimer-contrat/', supprimer_contrat, name='supprimer-contrat'),
    path('<int:pk>/modifier-contrat/', Contrat_mise_ajour.as_view(), name='modifier-contrat'),
    path('locataire-info/', ajouter_locataire_info , name='locataire-info'),
    path('locataire-detail/<int:locataire_id>/',detail_locataire , name='locataire-detail'),
    path('<int:pk>/delete-info/', supprimer_info, name='supprimer-info'),
    path('editinfo/<int:pk>/', Info_mise_ajour.as_view(), name='editinfo'),
    path('search-locataire/', search_maison , name='search-locataire'),




    ]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import HomeView,\
    ItemDetailView,\
    CheckoutView,\
    add_to_cart,\
    remove_from_cart,\
    OrderSummaryView,\
    remove_single_item_from_cart,\
    PaymentMethod,\
    AddCouponView,\
    CategoryListView,\
    RequestRefundView,\
    ProfileView,\
    product
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<category>', CategoryListView.as_view(), name='category-list'),
    path('product/<slug:slug>', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/<slug:slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug:slug>', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='check-out'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('payment/<payment_option>', PaymentMethod.as_view(), name='payment'),
    path('payment/<payment_option>', PaymentMethod.as_view(), name='payment'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('request-refund/<str:ref_code>', RequestRefundView.as_view(), name='request-refund'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

# for adding media file settings
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

houseProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('maison.urls')),
    path('index/', include('chambre.urls')),
    path('index/', include('contrat.urls')),
    path('index/', include('payement.urls')),
    path('index/', include('payement_e_e.urls')),
    path('', include('authentication.urls')),
    path('', include('django.contrib.auth.urls')),




    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

contrat/models.py
from django.db import models
from maison.models import Maison
from chambre.models import Chambre
from django.utils import timezone








SEXE_CHOICES = (
    ('M', 'Masculin'),
    ('F', 'Feminin'),


)


class Contrat(models.Model):
    """Models de Contrat"""
    nom_locataire = models.CharField(max_length=50 , null=False, blank=True)
    prenom_locataire= models.CharField(max_length=50)
    sexe=models.CharField(choices=SEXE_CHOICES, max_length=1)
    contact_no = models.CharField(max_length=15 , null = True ,blank=True)
    address = models.CharField(max_length=100, null= True, blank=True )
    email_address = models.EmailField(null=True, blank=True)
    maison =models.ForeignKey(Maison, on_delete=models.CASCADE)
    chambre = models.ForeignKey(Chambre, on_delete=models.CASCADE)
    caution = models.FloatField()
    date_contrat = models.DateTimeField(default=timezone.now)
    date_entree = models.DateTimeField(default=timezone.now,null=True, blank=True)
    date_sortie = models.DateTimeField(blank=True, null=True)
    profile_image = models.ImageField(upload_to='utilisateur_img/', null=True, blank=True)

    class Meta:
        permissions = (('peut voir  contrat', 'Peut voir contrat'),
                       ('peut voir detail des contrats', 'Peut voir detail des contrats'),)

    def get_absolute_url(self):
        return reverse('contrat-detail', args=str([self.pk]))

    def __str__(self):

        return '{0} {1}'.format(self.nom_locataire, self.prenom_locataire)

    def save(self, *args, **kwargs):  # Overriding default behaviour of save
     if self.chambre:
        self.chambre.statut = ""
     super(Contrat,self).save(*args, **kwargs)


    def is_overdue(self):
        if self.caution   is not self.chambre.prix *12 :
            return True
        return False

    def set_chambre_nom(self,chambre):
         if self.chambre:
              chambre =''.join(self.chambre, self.maison[:5])
              self.chambre=chambre






class LocataireInfo(models.Model):
        locataire = models.OneToOneField(Contrat, on_delete=models.CASCADE)
        information = models.TextField(max_length=400,null=False, blank=False)


        def __str__(self):

            return '{0} '.format( self.information)

contrat/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db.models import Q
from .models import Contrat, LocataireInfo
from maison.models import Maison
from chambre.models import Chambre



class ContratForm(forms.Form):
     maison =forms.ModelChoiceField(queryset=Maison.objects.all(), empty_label=None, label='Maison')
     chambre =forms.ModelChoiceField(queryset=Chambre.objects.all().filter(statut='L'), empty_label=None, label='Chambre')


     SEXE_CHOICES = (
      ('M', 'Masculin'),
      ('F', 'Feminin'),


     )

     nom_locataire= forms.CharField(
          label='Nom',
          widget=forms.TextInput()

      )
     prenom_locataire= forms.CharField(
           label='Prenom',
           widget=forms.TextInput()
       )

     sexe = forms.ChoiceField(choices=SEXE_CHOICES, widget=forms.RadioSelect(), help_text='Pardon Selectionnez le sexe:', initial='1')


     contact_no= forms.CharField(
              label='Contact',
              widget=forms.TextInput()
          )


     caution= forms.FloatField(
           label='Caution',
           widget=forms.TextInput()

       )


     address= forms.CharField(
          label='Adresse',
          widget=forms.TextInput()

      )
     email_address= forms.EmailField(
           label='Email',
           widget=forms.TextInput()
       )


     date_contrat= forms.DateTimeField(
          label='Date',
          widget=forms.TextInput()

      )


     date_entree= forms.DateTimeField(
            label='Date d''arrivee',
            widget=forms.TextInput()
        )

     date_sortie= forms.DateTimeField(
              label='Date de depart',
              widget=forms.TextInput(),
              required=False
          )

     profile_image = forms.ImageField(

        label='Photo',
        required=False
      )





     def clean_caution(self):
        chambre = self.cleaned_data['chambre']
        caution =self.cleaned_data['caution']
        if caution != chambre.prix*6:
            raise ValidationError(('Entrez une somme correcte!'))
        return caution


     def clean_email(self):
           email = self.cleaned_data['email_address'].lower()
           r = Contrat.objects.filter(email_address=email)
           if r.count:
               raise ValidationError("{0} existe deja".format(email))
           return email.lower()


     def clean_contact(self):
           contact = self.cleaned_data['contact_no']
           if contact == 'ayite':
              raise ValidationError("{0} est invalide".format(contact))
           return contact



     def clean_chambre_maison(self):
           cleaned_data =super(ContratForm,self).clean()
           chambre = cleaned_data.get('chambre')
           maison = cleaned_data.get('maison')


           if chambre and maison :

             if m.exists() and annee.exists() and locataire.exists():
                 raise ValidationError(('Ce payement est deja fait'))


           return cleaned_data







class LocataireInfoForm(forms.ModelForm):
         class Meta:

            model = LocataireInfo
            fields = ('locataire', 'information')
            labels={
                'locataire':'Locataire ',
                'information':'Information'



            }










"""
        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
"""
        # Remember to always return the cleaned data.

"""
     def clean_contrat(self):
            cleaned_data = super(ContratForm,self).clean()
            maison=cleaned_data.get('maison')
            chambre=cleaned_data.get('chambre')
            if maison is not chambre.maison:
                   raise ValidationError(('Vous n''est  pas autorise a signer ce contrat!'))





            if utilisateur.user_type !=3:
               raise ValidationError(('Vous n''est  pas autorise a signer ce contrat!'))

            return utilisateur
"""

contrat/views.py
from django.views.generic import (CreateView, DeleteView, ListView, FormView, UpdateView, ListView, DetailView)
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User, Group
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError
from django.db import transaction, IntegrityError
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import render
from django.views import generic
from django.views.generic import ListView, DetailView #Signup, ReservationForm, CheckInRequestForm
from .forms import ContratForm, LocataireInfoForm
from .models import Contrat, LocataireInfo
from payement.models import Annee
from chambre.models import Chambre
from payement.models import Payement
from payement_e_e.models import Payement_e_e
from maison.models import Maison

# Create your views here.



def list_contrat(request):
    if request.method == 'GET':
        liste_contrats = Contrat.objects.all()
        liste_maisons = Maison.objects.all()
        context = {
            "contrat": liste_contrats,
            "maison":liste_maisons

        }
    return render(request, 'contrat/list_locataire.html', context)




"""
def contrat(request):
    '''
    creer un contrat
    '''
    if request.method == 'POST':
        form = ContratForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contrat:list-contrat')
    else:
        form = ContratForm()
    total_contrat = Contrat.objects.all()
    ctx = {
        'form': form,
        'contrats': total_contrat,
    }
    return render(request, 'contrat/ajouter_contrat.html', ctx)
    """

def supprimer_contrat(request, pk):
   try:
       contrat = Contrat.objects.get(pk=pk)
       contrat.delete()

   except Contrat.DoesNotExist:
       contrat = None

   return redirect('contrat:liste-contrat')


def contrat(request):
    msg = None

    form = ContratForm()
    if request.method == 'POST':
        form = ContratForm(request.POST)
        if form.is_valid():
            nom_locataire = form.cleaned_data['nom_locataire']
            prenom_locataire = form.cleaned_data['prenom_locataire']
            sexe = form.cleaned_data['sexe']
            contact_no = form.cleaned_data['contact_no']
            address = form.cleaned_data['address']
            email_address = form.cleaned_data['email_address']
            maison = form.cleaned_data['maison']
            chambre = form.cleaned_data['chambre']
            caution = form.cleaned_data['caution']
            date_contrat = form.cleaned_data['date_contrat']
            date_entree = form.cleaned_data['date_entree']
            date_sortie = form.cleaned_data['date_sortie']
            profile_image=form.cleaned_data['profile_image']

            chambre = Chambre.objects.filter(nom=chambre, maison=maison)
            if chambre is not exists():
                 msg = 'Cette chambre ne se trouve pas dans cette maison'
            else:



                instance = Contrat(
                    nom_locataire=nom_locataire,
                    prenom_locataire=prenom_locataire,
                    sexe=sexe,
                    contact_no=contact_no,
                    address=address,
                    email_address=email_address,
                    maison =maison,
                    chambre=chambre,
                    caution=caution,
                    date_contrat=date_contrat,
                    date_entree=date_entree,
                    date_sortie=date_sortie,
                    profile_image=profile_image,
                    )
                instance.save()
                chambre.statut='O'
                chambre.save()

                return redirect('contrat:liste-contrat')

    else:
        form = ContratForm()

    context = {
        'form': form,
        'msg':msg,

    }
    return render(request, 'contrat/ajouter_contrat.html', context)


class Contrat_mise_ajour(LoginRequiredMixin, UpdateView):
       model = Contrat
       fields = '__all__'
       template_name = 'contrat/ajouter_contrat.html'

       def get_success_url(self):

           return reverse_lazy('contrat:liste-contrat')





def ajouter_locataire_info(request):
    """
      locataire info
    """
    if request.method == 'POST':
        form = LocataireInfoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contrat:liste-contrat')
    form = LocataireInfoForm()
    context = {
        "form": form
    }
    return render(request, 'contrat/locataire_info.html', context)



def detail_locataire(request, locataire_id):
        locataire = Contrat.objects.filter(id=locataire_id)
        detail =LocataireInfo.objects.filter(locataire__id=locataire_id)
        payement = Payement.objects.filter( locataire__id=locataire_id)[:12]
        payement_e = Payement_e_e.objects.filter( locataire__id=locataire_id)[:12]
        annee=Annee.objects.all()




        """
        def age(dob):
            today = date.today()
            return today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))

        instructorAge = age(details.dateOfBirth)
        qualifications = TeacherQualification.objects.all()
        """

        context = {
            'locataire': locataire,
            'detail': detail,
             'payement':payement,
             'annee':annee,
             'payement_e':payement_e,


        }
        return render(request, 'contrat/detail.html', context)






def supprimer_info(request, pk):
   try:
       info = LocataireInfo.objects.get(pk=pk)
       info.delete()

   except LocataireInfo.DoesNotExist:
       info = None

   return redirect('contrat:liste-contrat')





class Info_mise_ajour(LoginRequiredMixin, UpdateView):
    model = LocataireInfo
    fields = '__all__'
    template_name = 'contrat/locataire_info.html'

    def get_success_url(self):

        return reverse_lazy('contrat:liste-contrat')






def search_maison(request):
        query = request.GET.get('query')
        if not query:
            contrat = Contrat.objects.all()
        else:
            # title contains the query is and query is not sensitive to case.

            contrat =Contrat.objects.all().filter(maison__nom_maison__icontains=query)

        context = {
            'contrat': contrat,

        }
        return render(request, 'contrat/list_locataire.html', context)

templates/contrat/ajouter_contrat.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
 <div class="container-fluid">
   <div class="row">
     <div class="col-xl-2 col-md-6 mb-4 ">
   </div>

  <div class="col-xl-8 col-md-6 mb-4 ">
    {%if msg%}
    {{msg}}
    {%else%}
  <form method="post" enctype="multipart/form-data">

    {% csrf_token %}



          {{ form.nom_locataire|as_crispy_field }}

          {{ form.prenom_locataire|as_crispy_field }}
          {{ form.sexe|as_crispy_field }}
          {{ form.contact_no|as_crispy_field }}
            {{ form.address|as_crispy_field }}
              {{ form.email_address|as_crispy_field }}
           {{ form.maison|as_crispy_field }}
             {{ form.chambre|as_crispy_field }}
         {{ form.caution|as_crispy_field }}
          {{ form.profile_image|as_crispy_field }}





    <div class="form-row">
      <div class="form-group col-md-4 mb-0">
        {{ form.date_contrat|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.date_entree|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.date_sortie|as_crispy_field }}
      </div>

    </div>

    <div class="row">

   <div class="col-xl-8 col-md-6 mb-4 ">
     <a  ><button type="submit"  class="btn btn-primary btn-user btn-block"> <i class=" mdi mdi-database">Enregister</i></button></a>

  </div>


  <div class="col-xl-4 col-md-6 mb-4 ">
   <a  ><button type="submit"  class="btn btn-danger btn-user btn-block"> <i class=" mdi mdi-cancel">Annuler</i></button></a>

  </div>
    </div>

  </form>
  {%endif%}
    </div>

  <div class="col-xl-2 col-md-6 mb-4 ">
</div>
</div>
</div>



{% endblock %}

templates/contrat/list_locataire.html
{% extends "base.html" %}

{% block content %}






            <div class="container-fluid">




                            <style type="text/css">

                            .table-wrapper {
                                background: #fff;
                                padding: 20px 25px;
                                margin: 30px 0;
                            border-radius: 3px;
                                box-shadow: 0 1px 1px rgba(0,0,0,.05);
                            }
                            .table-title {
                            padding-bottom: 15px;
                            background: #4e73df;;
                            color: #fff;
                            padding: 16px 30px;
                            margin: -20px -25px 10px;
                            border-radius: 3px 3px 0 0;
                            }
                            .table-title h2 {
                            margin: 5px 0 0;
                            font-size: 24px;
                            }
                            .table-title .btn {
                            color: #566787;
                            float: right;
                            font-size: 13px;
                            background: #fff;
                            border: none;
                            min-width: 50px;
                            border-radius: 2px;
                            border: none;
                            outline: none !important;
                            margin-left: 10px;
                            }
                            .table-title .btn:hover, .table-title .btn:focus {
                                color: #566787;
                            background: #f2f2f2;
                            }
                            .table-title .btn i {
                            float: left;
                            font-size: 21px;
                            margin-right: 5px;
                            }
                            .table-title .btn span {
                            float: left;
                            margin-top: 2px;
                            }
                            table.table tr th, table.table tr td {
                                border-color: #e9e9e9;
                            padding: 12px 15px;
                            vertical-align: middle;
                            }
                            table.table tr th:first-child {
                            width: 60px;
                            }
                            table.table tr th:last-child {
                            width: 100px;
                            }
                            table.table-striped tbody tr:nth-of-type(odd) {
                              background-color: #fcfcfc;
                            }
                            table.table-striped.table-hover tbody tr:hover {
                            background: #f5f5f5;
                            }
                            table.table th i {
                                font-size: 13px;
                                margin: 0 5px;
                                cursor: pointer;
                            }
                            table.table td:last-child i {
                            opacity: 0.9;
                            font-size: 22px;
                                margin: 0 5px;
                            }
                            table.table td a {
                            font-weight: bold;
                            color: #566787;
                            display: inline-block;
                            text-decoration: none;
                            }
                            table.table td a:hover {
                            color: #2196F3;
                            }
                            table.table td a.settings {
                                color: #2196F3;
                            }
                            table.table td a.delete {
                                color: #F44336;
                            }
                            table.table td i {
                                font-size: 19px;
                            }
                            table.table .avatar {
                            border-radius: 50%;
                            vertical-align: middle;
                            margin-right: 10px;
                            }
                            .status {
                            font-size: 30px;
                            margin: 2px 2px 0 0;
                            display: inline-block;
                            vertical-align: middle;
                            line-height: 10px;
                            }
                            .text-success {
                                color: #10c469;
                            }
                            .text-info {
                                color: #62c9e8;
                            }
                            .text-warning {
                                color: #FFC107;
                            }
                            .text-danger {
                                color: #ff5b5b;
                            }
                            .pagination {
                                float: right;
                                margin: 0 0 5px;
                            }
                            .pagination li a {
                                border: none;
                                font-size: 13px;
                                min-width: 30px;
                                min-height: 30px;
                                color: #999;
                                margin: 0 2px;
                                line-height: 30px;
                                border-radius: 2px !important;
                                text-align: center;
                                padding: 0 6px;
                            }
                            .pagination li a:hover {
                                color: #666;
                            }
                            .pagination li.active a, .pagination li.active a.page-link {
                                background: #03A9F4;
                            }
                            .pagination li.active a:hover {
                                background: #0397d6;
                            }
                            .pagination li.disabled i {
                                color: #ccc;
                            }
                            .pagination li i {
                                font-size: 16px;
                                padding-top: 6px
                            }
                            .hint-text {
                                float: left;
                                margin-top: 10px;
                                font-size: 13px;
                            }


                            </style>




               <div class="row">
                   <div class="col-xl-12 col-md-12 mb-12 ">
            <div  class=" shadow ">
                <div class="table-wrapper ">

                    <div class="table-title  ">
                        <div class="row">
                            <div class="col-sm-5">

                              <h3>LISTE DES LOCATAIRES </h3>


        					</div>
        					<div class="col-sm-7">
        					{% if user.user_type == 3 %} 	<a href="{% url 'contrat:ajouter-contrat' %}" <button type="button" name="button" class="float-right btn btn-secondary"><i class=" mdi mdi-plus-circle  "></i></button> <span>Nouveau Locataire</span></a>{%endif%}

                      	</div>



                        </div>





                    </div>

                    <div class="row">
                                <div class="col-sm-4">

                      </div>
                                <div class="col-sm-4">
                                  <!-- Topbar Search -->
                                  <form class=" d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"    action="{% url 'contrat:search-locataire'  %}" method="get" accept-charset="utf-8">
                                    <div class="input-group">
                                      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="query">
                                      <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                          <i class="fas fa-search fa-sm"></i>
                                        </button>
                                      </div>
                                    </div>
                                  </form>

                                </div>

                                <div class="col-sm-4">

                      </div>
                            </div>
                    <table class="table table-striped table-hover">
                        <thead>

                            <tr>

                                <th>NOM</th>
                                <th>PRENOMS </th>
        						            <th>SEXE</th>
                                <th>CONTACTS</th>
        						             <th>DATE D'ENTREE</th>
                                  <th>DATE DE SORTIE</th>
                                  <th>ACTION</th>



                            </tr>

                        </thead>
                        <tbody>
                            {% for contrat in  contrat%}

                            <tr>


                                <td >  <a href="{% url 'contrat:locataire-detail' locataire_id=contrat.pk %}">{{contrat.nom_locataire}}</a></td>
                              <td > <a href="{% url 'contrat:locataire-detail' locataire_id=contrat.pk %}">{{contrat.prenom_locataire}}</a></td>
                              <td>{{contrat.sexe}}</td>
                              <td>{{contrat.contact_no}}</td>
                              <td>{{contrat.date_entree}}</td>
                                <td>{{contrat.date_sortie}}</td>


        						<td>
        						  {% if user.user_type == 3 %} 	<a href="{% url 'contrat:modifier-contrat' pk=contrat.pk %}" class="settings" title="Settings" data-toggle="tooltip"><i class=" mdi mdi-pencil   "></i></a>{%else%}
                      <a href="{% url 'contrat:liste-contrat' %}" class="settings" title="Settings" data-toggle="tooltip"><i class=" mdi mdi-pencil "></i></a>{%endif%}

        				      {% if user.user_type == 3 %}	<a  href="{% url 'contrat:supprimer-contrat' pk=contrat.pk %}" ><i class=" mdi mdi-delete contrat-i "></i></a>{%else%}<a  href="{% url 'contrat:liste-contrat' %}" ><i class=" mdi mdi-delete contrat-i"></i></a>{%endif%}
        						</td>

                            </tr>

                            {%endfor%}



                        </tbody>
                    </table>
        			<div class="clearfix">
                        <div class="hint-text">Montrant <strong>5</strong> sorties de <strong>25</strong> entrees</div>
                        <ul class="pagination">
                            <li class="page-item disabled"><a href="#">Precedent</a></li>
                            <li class="page-item"><a href="#" class="page-link">1</a></li>
                            <li class="page-item"><a href="#" class="page-link">2</a></li>
                            <li class="page-item active"><a href="#" class="page-link">3</a></li>
                            <li class="page-item"><a href="#" class="page-link">4</a></li>
                            <li class="page-item"><a href="#" class="page-link">5</a></li>
                            <li class="page-item"><a href="#" class="page-link">Suivant</a></li>
                        </ul>
                    </div>
                </div>








            </div>

        </div >





         </div >

         <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
           <div class="modal-dialog" role="document">
             <div class="modal-content">
               <div class="modal-header">
                 <h5 class="modal-title" id="exampleModalLabel">Vous voulez quittez cette page?</h5>
                 <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">×</span>
                 </button>
               </div>
               <div class="modal-body">Selectionnez "Se deconnecter" si dessous si vous etes prets a  quitter session.</div>
               <div class="modal-footer">
                 <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                 <a class="btn btn-primary" href="{% url 'authentication:login'%}">Se deconnecter</a>
               </div>
             </div>
           </div>
         </div>
            </div >




{% endblock content %}